# calico create -f calico-bgp-ip.yaml
apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  serviceExternalIPs:
  - cidr: 192.168.100.200/29
  serviceLoadBalancerIPs:
  - cidr: 192.168.100.208/28